workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    working_directory: agriconnect_v0

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Check files
        script: |
          pwd
          ls -la
          flutter --version

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build Android APK
        script: |
          flutter build apk --release

      - name: Build Android App Bundle
        script: |
          flutter build appbundle --release

      - name: Build iOS IPA
        script: |
          flutter build ipa --release --no-codesign

    artifacts:
      - agriconnect_v0/build/app/outputs/flutter-apk/*.apk
      - agriconnect_v0/build/app/outputs/bundle/release/*.aab
      - agriconnect_v0/build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - cyusaimpanochrispin@gmail.com
