workflows:
  sample-workflow:
    name: Codemagic Sample Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Clean project
        script: |
          flutter clean

      - name: Get Flutter packages
        script: |
          flutter pub get

      - name: Build Android APK
        script: |
          flutter build apk --release

      - name: Build Android App Bundle
        script: |
          flutter build appbundle --release

      - name: Build iOS IPA
        script: |
          flutter build ipa --release --no-codesign

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app

    publishing:
      email:
        recipients:
          - cyusaimpanochrispin@gmail.com
